<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_carscars  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeShowList"]=true;

		$this->events["BeforeShowView"]=true;


		$this->events["BeforeProcessList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, &$pageObject)
{

		if($_SESSION["mess"]){
	$pageObject->setProxyValue("email",$_SESSION["mess"]);
	$_SESSION["mess"] = "";
}
;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowView(&$xt, &$templatefile, &$values, &$pageObject)
{

		$pageObject->AddCSSFile("include/pgstyle.css");
$pageObject->AddCSSFile("lightgallery/lightgallery.css");
$pageObject->AddJSFile("lightgallery/lightgallery.js","lightgallery/lightgallery.css");
$pageObject->AddJSFile("lightgallery/lg-pager.js","lightgallery/lightgallery.js");
$pageObject->AddJSFile("lightgallery/lg-autoplay.js","lightgallery/lg-pager.js");
$pageObject->AddJSFile("lightgallery/lg-fullscreen.js","lightgallery/lg-autoplay.js");
$pageObject->AddJSFile("lightgallery/lg-zoom.js","lightgallery/lg-fullscreen.js");
$pageObject->AddJSFile("lightgallery/lg-hash.js","lightgallery/lg-zoom.js");
$pageObject->AddJSFile("lightgallery/lg-share.js","lightgallery/lg-hash.js");


;		
} // function BeforeShowView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

				// List page: Before process
function BeforeProcessList(&$pageObject)
{

		if( $_SESSION["UserID"]!="Guest" && $_SESSION["UserID"]!="" && !postvalue("page") && postvalue("a")!="page"){
	header("Location:carscars_list.php?page=list1");
	exit();
}


;		
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
