<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_carsform  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;

		$this->events["AfterAdd"]=true;


		$this->events["BeforeShowAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

		$values["car"] = $_SESSION["id"];
$email=$values["email"];

$url = "http://".$_SERVER["HTTP_HOST"].$_SERVER["REQUEST_URI"];
$p = strpos($url,"?");
$url = substr($url,0,$p)."?editid1=".$_SESSION["id"];
$url = str_replace("carsform_add.","carscars_view.",$url);
		
$mess="<table cellpadding=5px cellspacing=5px border=0><tr><td>".
$values["firstname"].",<br><br>
Thank you for your interest in <a href='".$url."'>".$_SESSION["Make"]."</a>, <a href='".$url."'>".$_SESSION["Model"]."</a>, <a href='".$url."'>".$_SESSION["YearOfMake"]."</a>. We will be back to your shortly.<br><br>
Dealership team.</td>
<td width=200px><a href='".$url."'><img width=200px src='".GetWebRootPath().$_SESSION["Email_Picture"]."' /></a></td></tr></table>";

$subject="Request a Free Price Quote";
	
$ret=runner_mail(array('to' => $email, 'subject' => $subject, 'htmlbody' => $mess));
if(!$ret["mailed"])
{
	$message = $ret["message"];
	return false; 
}
else{
	$_SESSION["mess"] = $email;
	return true;
}
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		$pageObject->setProxyValue('saved', true);  
$pageObject->stopPRG = true;


;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, &$pageObject)
{

		$pageObject->AddCSSFile("lightgallery/lightgallery.css");
$pageObject->AddJSFile("lightgallery/lightgallery.js","lightgallery/lightgallery.css");
$pageObject->AddJSFile("lightgallery/lg-pager.js","lightgallery/lightgallery.js");
$pageObject->AddJSFile("lightgallery/lg-autoplay.js","lightgallery/lg-pager.js");
$pageObject->AddJSFile("lightgallery/lg-fullscreen.js","lightgallery/lg-autoplay.js");
$pageObject->AddJSFile("lightgallery/lg-zoom.js","lightgallery/lg-fullscreen.js");
$pageObject->AddJSFile("lightgallery/lg-hash.js","lightgallery/lg-zoom.js");
$pageObject->AddJSFile("lightgallery/lg-share.js","lightgallery/lg-hash.js");

$pageObject->AddCSSFile("include/header.css");

;		
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
